### ISSUE TITLE
Confusng [WARNING] Descriptor action failed for unknown service ... when a descriptor fails to upload

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#16]
After successfully building second descriptor and trying to upload it to 8 HSDirs, 1/8 failed with the following message:

`[WARNING]: Descriptor action failed for unknown service 5tqw3kwwuy7sf3zhdpvz6valtyjnbsuxasx52afnuezr6hkmbsnqrtad to $51E1CF613FD6F9F11FE24743C91D6F9981807D82~torpidsDEisppro3`

As per chat, the suspect is:

`            if self._address_is_instance(desc_event.address):
                 logger.info("Description fetch failed for instance %s to %s", desc_event.address, desc_event.directory)
             elif self._address_is_frontend(desc_event.address):
                 logger.warning("Descriptor upload failed for frontend %s to %s", desc_event.address, desc_event.directory)
             else:
                 logger.warning("Descriptor action failed for unknown service %s to %s", desc_event.address, desc_event.directory)`

This is not something serious though, as the frondend is still up and the onionbalance daemon is not killed, but worth fixing. On super heavy loads is quite easy to catch a HSDir to which the upload of the descriptor would fail, so need to improve little bit.

**Comment by asn-d6** [comment]
OK the "unknown" part of the log message has been  fixed in ba560d0 and in 17afa3e I added some more diagnostics to perhaps fix the underlying descriptor upload failure here. I'll close this ticket for now, but feel free to reopen it if it occurs again.
