### ISSUE TITLE
UI: Limit the number of backend address slots onionbalance config generator will accept

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#22]
As we describe in the documentation currently we can use up to 8 backend instances. If this will be increased in the future it's quite possible but for the time being, wouldn't it make sense to limit the number of backend instances the user can enter in both `onionbalance-config` interactive mode, and `-n` parameter in command line? Right not `onionbalance-config` will happily accept for Number of instances to create 20000, and it only states the default value [2], makes sense to specify: `Number of instances to create (min. 1 max. 8) [2]:` or something similar. What do you think?

**Comment by asn-d6** [comment]
Good point.

I decided to go simple and just add an informative min/max msg to it in 3ff3aa28c00cf93046d142d0f3e46234c5fa52ac.

I think this should be OK for now!
