### ISSUE TITLE
v3: Config file filtering: prevent accidentally nominating the frontend as a backend instance

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#26]
To sanitize and filter config file as much as possible, users should be prevented from accidentally nominating the frontend onion address as a backend instance as well.

If `Loaded instance HS-v3-address.onion` matches (at least one) element in `instances` it should print a config file `[ERROR]` and exit.

**Comment by asn-d6** [comment]
Good point. Done in 1561120!
