### ISSUE TITLE
Bug: onionbalance does not start with onionbalance-config generated v3 onion secret keys

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#28]
Most probably when #17 was merged, to support native Tor v3 onion secret keys, the previously onionbalance-config generated v3 onion secret keys cannot be loaded any more. Fails with:

`[WARNING]: Service private key not in Tor format either ('Tor key does not start with Tor header'). Aborting.`

**Comment by gits7r** [comment]
To reproduce:

run `onionbalance-config`, and when asked for the v3 secret key path, leave blank so onionbalance can generate a new one.

try to start onionbalance with the newly created config file + newly created v3 onion hostname. It will fail by looking for the Tor header. I think we made it  strict rather than also possible, so now it only works with onions v3 secret keys in Tor's format.

**Comment by asn-d6** [comment]
Jeez that was embarassing. 35d5b0a should fix it. Thanks a lot!
