### ISSUE TITLE
I'd like to test v3

### ISSUE THREAD

**Issue by afshar-mohammad** [torproject/onionbalance#3]
Hi, I just wanted to inform you I'd like to test v3 onionbalance and you can count on it, but I'm very busy this week. I'll set up as soon as I get some spare time. 

Thanks for all your efforts

**Comment by asn-d6** [comment]
Great. Looking forward to your testing!

Next week I will start development on it again (adding installation scripts, docs, etc.) so things might be a bit more fluid.

(Feel free to open the ticket again if you have any questions or comments)
