### ISSUE TITLE
Can't install using setup.py

### ISSUE THREAD

**Issue by afshar-mohammad** [torproject/onionbalance#4]
I cloned this git repo and installed all dependencies (python 3.8.1). My `pip3 list` looks like this:

```
Package      Version
------------ -------
future       0.18.2 
pip          20.0.2 
pycrypto     2.6.1  
PyYAML       5.3    
setproctitle 1.1.10 
setuptools   41.2.0 
stem         1.8.0
```

Now when I try `python3 setup.py install` I get this error:

```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    exec(init_file.read(), module_info)
  File "<string>", line 9, in <module>
KeyError: "'__name__' not in globals"
```

**Comment by asn-d6** [comment]
Hm, this seems to be a bug indeed. I will try to fix ASAP.

Does it work if you try to run from the source directory directly? Like `python3 onionbalance.py` or `$ python3 onionbalance-config.py`?

**Comment by asn-d6** [comment]
Hey. Let me know if https://github.com/asn-d6/onionbalance/commit/7a191189cb701e8c064e1bb1ca26159371625439 fixed your issue.

**Comment by afshar-mohammad** [comment]
Yes, 7a191189cb701e8c064e1bb1ca26159371625439 fixed the problem.
