### ISSUE TITLE
Tor current key problem v3

### ISSUE THREAD

**Issue by novaws** [torproject/onionbalance#47]
Good day, i have problem with current domain key, when import inside onion balance.

```
[WARNING]: Service private key not in OBv3 format ('('Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])'). Trying tor's format...
```

but key i get from current instance.
inside hs_keys dir, 3 files.

```
hostname 
hs_ed25519_public_key
hs_ed25519_secret_key
```

Tor 0.4.6.8
onionbalance 0.2.2

**Comment by rhatto** [comment]
This warning just means that the keys are not in the Onionbalance v3 PEM format.

Onionbalance [tries opportunistically][] to load keys in this format before falling back to the Tor binary format.

[tries opportunistically]: https://gitlab.torproject.org/tpo/onion-services/onionbalance/-/blob/140cf1fcd5949a51968cfd5e1726d9b756d6c844/onionbalance/hs_v3/service.py#L105
