### ISSUE TITLE
`paramiko` is needed

### ISSUE THREAD

**Issue by afshar-mohammad** [torproject/onionbalance#5]
`paramiko` was not mentioned in https://lists.torproject.org/pipermail/tor-dev/2020-January/014142.html as a dependency. If you try to run onionbalance without `paramiko` you'll end up with this error:

```
Traceback (most recent call last):
  File "onionbalance.py", line 7, in <module>
    import onionbalance.hs_v3.manager
  File "../onionbalance/onionbalance/hs_v3/manager.py", line 13, in <module>
    from onionbalance.hs_v3 import onionbalance
  File "../onionbalance/onionbalance/hs_v3/onionbalance.py", line 12, in <module>
    from onionbalance.hs_v3 import hashring
  File "../onionbalance/onionbalance/hs_v3/hashring.py", line 7, in <module>
    from cryptography.hazmat.primitives import serialization
ModuleNotFoundError: No module named 'cryptography'
```

I solved the issue by issuing `pip3 install paramiko`.

**Comment by asn-d6** [comment]
I don't think you need to install paramiko, but you definitely need the `cryptography` module. Mentioned it here: https://github.com/asn-d6/onionbalance/commit/5bc8dcfa58009f51aed77ba7977b74d541dfbd92

Also hopefully the installation scripts improvements of https://github.com/asn-d6/onionbalance/commit/7a191189cb701e8c064e1bb1ca26159371625439 should cover that too.
