### ISSUE TITLE
Onionbalance v. HAProxy

### ISSUE THREAD

**Issue by elimisteve** [torproject/onionbalance#7]
I just read through much of the docs but still have the following fundamental question: what does onionbalance do that can't be done by HAProxy running as an onion service that load balances across several backend servers also running as their own onion services?

Thanks!

**Comment by elimisteve** [comment]
Traffic doesn't actually flow through Onionbalance and there's a standardized way for the Tor network to reply with the URL to a backend server? Is that the difference?

**Comment by asn-d6** [comment]
Hello @elimisteve ,

the main difference is that HAProxy does the load-balancing on the application-layer, whereas Onionbalance load balances on the Tor protocol layer. There is lots of things going on in the onion services protocol before traffic hits the application-layer, so load balancing before that is extremely useful. You can think of it as DNS load-balancing but for onion services (where DNS does not exist).

This is something that we might want to add to the docs (feel free to open a PR if you'd like to do a patch).

**Comment by asn-d6** [comment]
Closing this. Feel free to reopen if needed.

**Comment by elimisteve** [comment]
@asn-d6 Makes sense, thanks!
