### ISSUE TITLE
doc generation import failure

### ISSUE THREAD

**Issue by FedericoCeratto** [torproject/onionbalance#8]
`PYTHONPATH=. http_proxy='http://127.0.0.1:9/' python3 -m sphinx -N -v -v -v -v -E -bhtml docs/ docs/_build/html` fails with sphinx 1.8.5-7 on Debian with `ImportError: No module named onionbalance.config_generator.config_generator`

If `sphinxcontrib.autoprogram` is removed from conf.py it works

**Comment by asn-d6** [comment]
Hello,

commit https://github.com/asn-d6/onionbalance/commit/5fa46e8697a99b8cd66a29db5613836fe94deb25 should address this issue.

Please reopen the ticket if you are still having difficulties here.

Thanks for the report!
